# Generated by Django 5.1.7 on 2025-03-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('asx_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('ann_date', models.DateField(blank=True, null=True)),
                ('net_operating_cash_flow', models.FloatField(blank=True, null=True)),
                ('exploration_spend', models.FloatField(blank=True, null=True)),
                ('development_production_spend', models.FloatField(blank=True, null=True)),
                ('staff_costs', models.FloatField(blank=True, null=True)),
                ('admin_costs', models.FloatField(blank=True, null=True)),
                ('other_costs', models.FloatField(blank=True, null=True)),
                ('net_cash_invest', models.FloatField(blank=True, null=True)),
                ('cashflow_total', models.FloatField(blank=True, null=True)),
                ('bank_balance', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('forecast_net_operating', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField()),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('bank_balance', models.FloatField(blank=True, null=True)),
                ('enterprise_value', models.FloatField(blank=True, null=True)),
                ('ev_resource_per_ounce_ton', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
