# Generated by Django 5.1.7 on 2025-03-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('asx_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalRaises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('raise_type', models.CharField(max_length=50)),
                ('priority_commodities', models.JSONField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_raises', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255)),
                ('priority_commodities', models.JSONField(blank=True, null=True)),
                ('base_remuneration', models.FloatField(blank=True, null=True)),
                ('total_remuneration', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('ann_date', models.DateField(blank=True, null=True)),
                ('net_operating_cash_flow', models.FloatField(blank=True, null=True)),
                ('exploration_spend', models.FloatField(blank=True, null=True)),
                ('development_production_spend', models.FloatField(blank=True, null=True)),
                ('staff_costs', models.FloatField(blank=True, null=True)),
                ('admin_costs', models.FloatField(blank=True, null=True)),
                ('other_costs', models.FloatField(blank=True, null=True)),
                ('net_cash_invest', models.FloatField(blank=True, null=True)),
                ('cashflow_total', models.FloatField(blank=True, null=True)),
                ('bank_balance', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('forecast_net_operating', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField()),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('bank_balance', models.FloatField(blank=True, null=True)),
                ('enterprise_value', models.FloatField(blank=True, null=True)),
                ('ev_resource_per_ounce_ton', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('trade_value', models.FloatField(blank=True, null=True)),
                ('total_shares', models.FloatField(blank=True, null=True)),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('previous_price', models.FloatField(blank=True, null=True)),
                ('week_price_change', models.FloatField(blank=True, null=True)),
                ('month_price_change', models.FloatField(blank=True, null=True)),
                ('year_price_change', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_trend', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=255)),
                ('activity_date_per_day', models.DateField(blank=True, null=True)),
                ('activity', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('intersect', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('percentage_per_metre', models.FloatField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255)),
                ('value', models.FloatField(blank=True, null=True)),
                ('project_commodities', models.CharField(max_length=255)),
                ('project_area', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('ann_date', models.DateField(blank=True, null=True)),
                ('asx_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='api.company')),
            ],
        ),
    ]
