version: 0.2
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:050107530013:task-definition/${AWSECS_FAMILY}"
        LoadBalancerInfo:
          ContainerName: "${AWSECS_CONTAINER}"
          ContainerPort: 80



